// src/config/access.config.ts


export type AccessConfig = {

    rateLimit: {

        /**
         * Fallback when the server does not provide
         * a usable Retry-After value.
         */
        defaultRetryAfterMs: number;


        /**
         * Maximum delay generated by our own
         * rate-limit backoff policy.
         */
        maxRetryAfterMs: number;


        backoffMultiplier: number;


        respectRetryAfterHeader: boolean;


        /**
         * Example:
         *
         * 0.15 = ±15%
         */
        jitterRatio: number;
    };


    transientErrors: {

        /**
         * Initial retry delay by failure type.
         */
        timeoutRetryMs: number;

        dnsRetryMs: number;

        connectionRetryMs: number;

        siteUnavailableRetryMs: number;


        /**
         * Maximum delay generated by transient
         * failure backoff.
         *
         * Kept independent from rate-limit config.
         */
        maxRetryAfterMs: number;


        /**
         * Used with consecutiveFailures.
         */
        backoffMultiplier: number;


        /**
         * Retry randomization specific to transient
         * failures.
         */
        jitterRatio: number;


        /**
         * Useful particularly for 503 responses,
         * where Retry-After may be provided.
         */
        respectRetryAfterHeader: boolean;
    };


    detection: {

        maxBodyInspectionBytes: number;


        minimumSignalConfidence: number;
    };
};


export const ACCESS_CONFIG: AccessConfig = {

    rateLimit: {

        defaultRetryAfterMs:
            30_000,

        maxRetryAfterMs:
            15 * 60_000,

        backoffMultiplier:
            2,

        respectRetryAfterHeader:
            true,

        jitterRatio:
            0.15,
    },


    transientErrors: {

        timeoutRetryMs:
            5_000,

        dnsRetryMs:
            10_000,

        connectionRetryMs:
            5_000,

        siteUnavailableRetryMs:
            15_000,

        maxRetryAfterMs:
            5 * 60_000,

        backoffMultiplier:
            2,

        jitterRatio:
            0.15,

        respectRetryAfterHeader:
            true,
    },


    detection: {

        maxBodyInspectionBytes:
            256 * 1024,

        minimumSignalConfidence:
            0.60,
    },
};