// src/access-controller/policies/rate-limit.policy.ts

import type {
    AccessEvaluation,
} from '../../core/contracts/access-evaluation.js';

import type {
    FetchHeaders,
} from '../../core/contracts/fetch-envelope.js';

import type {
    DomainAccessState,
} from '../state/state-store.js';

import type {
    AccessPolicy,
    AccessPolicyContext,
    AccessSignal,
} from '../types.js';


/**
 * Injected functions make time and jitter deterministic
 * during unit tests.
 */
export type RateLimitPolicyDependencies = {
    now?: () => number;
    random?: () => number;
};


export class RateLimitPolicy
implements AccessPolicy {

    private readonly now:
        () => number;

    private readonly random:
        () => number;


    constructor(
        dependencies:
            RateLimitPolicyDependencies = {},
    ) {

        this.now =
            dependencies.now
            ?? Date.now;

        this.random =
            dependencies.random
            ?? Math.random;
    }


    supports(
        signal: AccessSignal,
    ): boolean {

        return (
            signal.reason
            === 'RATE_LIMITED'
        );
    }


    async evaluate(
        signal: AccessSignal,
        context: AccessPolicyContext,
    ): Promise<AccessEvaluation> {

        /**
         * Defensive guard.
         *
         * AccessController should normally call
         * supports() before evaluate().
         */
        if (
            !this.supports(
                signal,
            )
        ) {

            throw new Error(
                `RateLimitPolicy does not support reason: ${signal.reason}`,
            );
        }


        const {
            job,
            envelope,
            config,
            stateStore,
        } = context;


        this.validateConfig(
            config.rateLimit,
        );


        const domain =
            this.getDomain(
                job.url,
            );


        const nowMs =
            this.now();


        const previousState =
            await stateStore
                .getDomainState(
                    domain,
                );


        const state =
            this.createState(
                previousState,
                nowMs,
            );


        /**
         * Number of rate-limit events that happened
         * before the current one.
         */
        const previousRateLimits =
            this.normalizeCounter(
                state
                    .consecutiveRateLimits,
            );


        /**
         * Exponential delay generated by OUR policy.
         *
         * First 429:
         * default * multiplier^0
         *
         * Second:
         * default * multiplier^1
         *
         * Third:
         * default * multiplier^2
         */
        const backoffDelayMs =
            this.calculateBackoff(
                config
                    .rateLimit
                    .defaultRetryAfterMs,

                config
                    .rateLimit
                    .backoffMultiplier,

                previousRateLimits,

                config
                    .rateLimit
                    .maxRetryAfterMs,
            );


        /**
         * Retry-After supplied by the server,
         * if valid and enabled by configuration.
         */
        const serverRetryAfterMs =
            config
                .rateLimit
                .respectRetryAfterHeader

                ? this.parseRetryAfter(
                    envelope.headers,
                    nowMs,
                )

                : undefined;


        /**
         * Never retry sooner than either:
         *
         * - our calculated backoff
         * - the server's Retry-After
         */
        const baseDelayMs =
            Math.max(
                backoffDelayMs,
                serverRetryAfterMs
                    ?? 0,
            );


        /**
         * Apply jitter.
         *
         * IMPORTANT:
         *
         * If Retry-After exists, jitter is not
         * allowed to reduce the delay below the
         * server-provided minimum.
         */
        let retryAfterMs =
            this.applyJitter(
                baseDelayMs,
                config
                    .rateLimit
                    .jitterRatio,
            );


        if (
            serverRetryAfterMs
            !== undefined
        ) {

            retryAfterMs =
                Math.max(
                    retryAfterMs,
                    serverRetryAfterMs,
                );
        }


        /**
         * Apply our configured upper bound.
         *
         * Exception:
         *
         * If we explicitly chose to respect
         * Retry-After and the server requested a
         * delay longer than our local maximum,
         * do NOT silently retry earlier than the
         * server requested.
         */
        if (
            serverRetryAfterMs
                === undefined

            || serverRetryAfterMs
                <= config
                    .rateLimit
                    .maxRetryAfterMs
        ) {

            retryAfterMs =
                Math.min(
                    retryAfterMs,
                    config
                        .rateLimit
                        .maxRetryAfterMs,
                );

        } else {

            retryAfterMs =
                Math.max(
                    retryAfterMs,
                    serverRetryAfterMs,
                );
        }


        retryAfterMs =
            Math.max(
                0,
                Math.round(
                    retryAfterMs,
                ),
            );


        /**
         * Current rate-limit event is now recorded.
         */
        state.consecutiveRateLimits =
            previousRateLimits + 1;


        state.lastReason =
            'RATE_LIMITED';


        state.cooldownUntil =
            new Date(
                nowMs
                + retryAfterMs,
            ).toISOString();


        state.updatedAt =
            new Date(
                nowMs,
            ).toISOString();


        await stateStore
            .setDomainState(
                domain,
                state,
            );


        return {
            decision:
                'RETRY_LATER',

            reason:
                'RATE_LIMITED',

            retryAfterMs,

            message:
                `Rate limited. Retry after ${Math.ceil(
                    retryAfterMs / 1000,
                )}s.`,
        };
    }


    /**
     * Retry-After can be:
     *
     * 120
     *
     * OR
     *
     * Wed, 21 Oct 2015 07:28:00 GMT
     */
    private parseRetryAfter(
        headers: FetchHeaders,
        nowMs: number,
    ): number | undefined {

        const rawHeader =
            headers[
                'retry-after'
            ];


        if (
            rawHeader
            === undefined
        ) {

            return undefined;
        }


        const values =
            Array.isArray(
                rawHeader,
            )
                ? rawHeader
                : [rawHeader];


        /**
         * Multiple Retry-After values are unusual.
         *
         * If present, choose the first value that
         * parses correctly.
         */
        for (
            const rawValue
            of values
        ) {

            const parsed =
                this.parseRetryAfterValue(
                    rawValue,
                    nowMs,
                );


            if (
                parsed !== undefined
            ) {

                return parsed;
            }
        }


        return undefined;
    }


    private parseRetryAfterValue(
        rawValue: string,
        nowMs: number,
    ): number | undefined {

        const value =
            rawValue.trim();


        if (
            value.length === 0
        ) {

            return undefined;
        }


        /**
         * RFC delay-seconds:
         *
         * non-negative decimal integer.
         *
         * "0" is valid.
         */
        if (
            /^\d+$/.test(
                value,
            )
        ) {

            const seconds =
                Number(
                    value,
                );


            if (
                !Number.isSafeInteger(
                    seconds,
                )
                || seconds < 0
            ) {

                return undefined;
            }


            const milliseconds =
                seconds * 1000;


            if (
                !Number.isSafeInteger(
                    milliseconds,
                )
            ) {

                return undefined;
            }


            return milliseconds;
        }


        /**
         * Try HTTP-date.
         */
        const timestamp =
            Date.parse(
                value,
            );


        if (
            !Number.isFinite(
                timestamp,
            )
        ) {

            return undefined;
        }


        /**
         * An HTTP-date already in the past means
         * no additional server-requested delay.
         */
        return Math.max(
            0,
            timestamp - nowMs,
        );
    }


    private calculateBackoff(
        defaultDelayMs: number,
        multiplier: number,
        consecutiveRateLimits: number,
        maximumDelayMs: number,
    ): number {

        const exponential =
            defaultDelayMs
            * Math.pow(
                multiplier,
                consecutiveRateLimits,
            );


        /**
         * Protect against numerical overflow.
         */
        if (
            !Number.isFinite(
                exponential,
            )
        ) {

            return maximumDelayMs;
        }


        return Math.min(
            exponential,
            maximumDelayMs,
        );
    }


    /**
     * Symmetric jitter:
     *
     * jitterRatio 0.15
     *
     * gives approximately:
     *
     * -15% ... +15%
     */
    private applyJitter(
        delayMs: number,
        jitterRatio: number,
    ): number {

        if (
            delayMs <= 0
            || jitterRatio === 0
        ) {

            return delayMs;
        }


        /**
         * Defensive normalization in case a custom
         * random implementation returns outside
         * the expected 0..1 range.
         */
        const randomValue =
            Math.min(
                1,
                Math.max(
                    0,
                    this.random(),
                ),
            );


        const normalized =
            randomValue * 2 - 1;


        const jitter =
            delayMs
            * jitterRatio
            * normalized;


        return Math.max(
            0,
            delayMs + jitter,
        );
    }


    private createState(
        existing:
            DomainAccessState | null,

        nowMs: number,
    ): DomainAccessState {

        if (
            existing
        ) {

            return {
                ...existing,
            };
        }


        return {
            consecutiveRateLimits:
                0,

            consecutiveFailures:
                0,

            updatedAt:
                new Date(
                    nowMs,
                ).toISOString(),
        };
    }


    private normalizeCounter(
        value: number,
    ): number {

        if (
            !Number.isSafeInteger(
                value,
            )
            || value < 0
        ) {

            return 0;
        }


        return value;
    }


    /**
     * Kept local so AccessController does not
     * depend on request-manager/url-utils.ts.
     *
     * Later URL/domain helpers can move into
     * a shared core utility module.
     */
    private getDomain(
        url: string,
    ): string {

        try {

            return new URL(
                url,
            )
                .hostname
                .toLowerCase();

        } catch {

            throw new Error(
                `RateLimitPolicy received invalid job URL: ${url}`,
            );
        }
    }


    private validateConfig(
        config:
            AccessPolicyContext[
                'config'
            ]['rateLimit'],
    ): void {

        if (
            !Number.isFinite(
                config
                    .defaultRetryAfterMs,
            )
            || config
                .defaultRetryAfterMs < 0
        ) {

            throw new Error(
                'defaultRetryAfterMs must be a non-negative number.',
            );
        }


        if (
            !Number.isFinite(
                config
                    .maxRetryAfterMs,
            )
            || config
                .maxRetryAfterMs < 0
        ) {

            throw new Error(
                'maxRetryAfterMs must be a non-negative number.',
            );
        }


        if (
            config
                .maxRetryAfterMs
            <
            config
                .defaultRetryAfterMs
        ) {

            throw new Error(
                'maxRetryAfterMs must be greater than or equal to defaultRetryAfterMs.',
            );
        }


        if (
            !Number.isFinite(
                config
                    .backoffMultiplier,
            )
            || config
                .backoffMultiplier < 1
        ) {

            throw new Error(
                'backoffMultiplier must be greater than or equal to 1.',
            );
        }


        if (
            !Number.isFinite(
                config
                    .jitterRatio,
            )
            || config
                .jitterRatio < 0
            || config
                .jitterRatio > 1
        ) {

            throw new Error(
                'jitterRatio must be between 0 and 1.',
            );
        }
    }
}